# Generated by Django 4.1 on 2022-10-19 07:39

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='acceptSupplyRequests',
            fields=[
                ('acceptSupplyRequests_id', models.AutoField(primary_key=True, serialize=False)),
                ('arequest_supply_department', models.CharField(max_length=50, verbose_name='arequest_supply_department')),
                ('arequest_supply_itemname', models.CharField(max_length=50, verbose_name='arequest_supply_itemname')),
                ('arequest_supply_description', models.CharField(max_length=255, verbose_name='arequest_supply_description')),
                ('arequest_supply_unit', models.CharField(max_length=50, verbose_name='arequest_supply_unit')),
                ('arequest_supply_quantity', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='arequest_supply_quantity')),
                ('arequest_supply_remaining', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='arequest_supply_remaining')),
                ('arequest_supply_status', models.CharField(max_length=50, verbose_name='arequest_supply_status')),
                ('current_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='arequest_current_date')),
            ],
            options={
                'db_table': 'acceptSupplyRequests',
            },
        ),
        migrations.CreateModel(
            name='deliveryequipment',
            fields=[
                ('deliveryequipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_equipment_itemname', models.CharField(max_length=50, verbose_name='delivery_equipment_itemname')),
                ('delivery_equipment_description', models.CharField(max_length=255, verbose_name='delivery_equipment_description')),
                ('delivery_equipment_brand', models.CharField(max_length=50, verbose_name='delivery_equipment_brand')),
                ('delivery_equipment_quantity', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='delivery_equipment_quantity')),
                ('delivery_equipment_remaining', models.CharField(max_length=50, verbose_name='delivery_equipment_remaining')),
                ('current_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='delivery_current_date')),
            ],
            options={
                'db_table': 'deliveryequipment',
            },
        ),
        migrations.CreateModel(
            name='deliverysupply',
            fields=[
                ('deliverysupply_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_supply_itemname', models.CharField(max_length=50, verbose_name='delivery_supply_itemname')),
                ('delivery_supply_description', models.CharField(max_length=255, verbose_name='delivery_supply_description')),
                ('delivery_supply_unit', models.CharField(max_length=50, verbose_name='delivery_supply_unit')),
                ('delivery_supply_quantity', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='delivery_supply_quantity')),
                ('delivery_supply_remaining', models.CharField(max_length=50, verbose_name='delivery_supply_remaining')),
                ('current_date', models.DateTimeField(auto_now_add=True, verbose_name='delivery_current_date')),
            ],
            options={
                'db_table': 'deliverysupply',
            },
        ),
        migrations.CreateModel(
            name='equipmentmainstorage',
            fields=[
                ('equipmentmainstorage_id', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=50, verbose_name='ItemName')),
                ('Description', models.CharField(max_length=255, verbose_name='Description')),
                ('Brand', models.CharField(max_length=50, verbose_name='Brand')),
                ('Quantity', models.DecimalField(decimal_places=0, max_digits=50, verbose_name='Quantity')),
                ('Remaining', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Remaining')),
            ],
            options={
                'db_table': 'equipmentmainstorage',
            },
        ),
        migrations.CreateModel(
            name='limitrecords',
            fields=[
                ('limit_id', models.AutoField(primary_key=True, serialize=False)),
                ('limit_item_name', models.CharField(max_length=50, verbose_name='limit_item_name')),
                ('limit_description', models.CharField(max_length=255, verbose_name='limit_description')),
                ('limit_unit', models.CharField(max_length=50, verbose_name='limit_unit')),
                ('limit_quantity', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='limit_quantity')),
                ('limit_department', models.CharField(max_length=50, verbose_name='limit_department')),
                ('limit_addquantity', models.CharField(max_length=50, verbose_name='limit_addquantity')),
            ],
            options={
                'db_table': 'limitrecords',
            },
        ),
        migrations.CreateModel(
            name='requestequipment',
            fields=[
                ('requestequipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_equipment_itemname', models.CharField(max_length=50, verbose_name='request_equipment_itemname')),
                ('request_equipment_description', models.CharField(max_length=255, verbose_name='request_equipment_description')),
                ('request_equipment_brand', models.CharField(max_length=50, verbose_name='request_equipment_brand')),
                ('request_equipment_unit', models.CharField(max_length=50, verbose_name='request_equipment_unit')),
                ('request_equipment_quantity', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='request_equipment_quantity')),
                ('request_equipment_department', models.CharField(max_length=50, verbose_name='request_equipment_department')),
                ('request_equipment_status', models.CharField(max_length=50, verbose_name='request_equipment_status')),
                ('current_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='request_current_date')),
            ],
            options={
                'db_table': 'requestequipment',
            },
        ),
        migrations.CreateModel(
            name='requestsupply',
            fields=[
                ('requestsupply_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_supply_itemname', models.CharField(max_length=50, verbose_name='request_supply_itemname')),
                ('request_supply_description', models.CharField(max_length=255, verbose_name='request_supply_description')),
                ('request_supply_unit', models.CharField(max_length=50, verbose_name='request_supply_unit')),
                ('request_supply_quantity', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='request_supply_quantity')),
                ('request_supply_remaining', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='request_supply_remaining')),
                ('request_supply_department', models.CharField(max_length=50, verbose_name='request_supply_department')),
                ('request_supply_status', models.CharField(max_length=50, verbose_name='request_supply_status')),
                ('current_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='request_current_date')),
            ],
            options={
                'db_table': 'requestsupply',
            },
        ),
        migrations.CreateModel(
            name='returnequipment',
            fields=[
                ('returnequipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('return_equipment_property_no', models.CharField(max_length=50, verbose_name='return_equipment_property_no')),
                ('return_equipment_itemname', models.CharField(max_length=50, verbose_name='return_equipment_itemname')),
                ('return_equipment_description', models.CharField(max_length=255, verbose_name='return_equipment_description')),
                ('return_equipment_brand', models.CharField(max_length=50, verbose_name='return_equipment_brand')),
                ('return_equipment_yearacquired', models.CharField(max_length=50, verbose_name='return_yearacquired')),
                ('return_equipment_issued_to', models.CharField(max_length=50, verbose_name='return_equipment_issued_to')),
                ('return_equipment_model_no', models.CharField(max_length=50, verbose_name='return_equipment_model_no')),
                ('return_equipment_serial_no', models.CharField(max_length=50, verbose_name='return_equipment_serial_no')),
                ('return_equipment_certifiedcorrect', models.CharField(max_length=50, verbose_name='return_equipment_certifiedcorrect')),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='return_date')),
            ],
            options={
                'db_table': 'returnequipment',
            },
        ),
        migrations.CreateModel(
            name='storagemapping',
            fields=[
                ('storagemapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=50, verbose_name='Category')),
                ('ItemName', models.CharField(max_length=50, verbose_name='ItemName')),
                ('Location', models.CharField(max_length=50, verbose_name='Location')),
                ('CabinetNo', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Cabinet')),
                ('ShelfNo', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Shelf')),
                ('LayerNo', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Layer')),
            ],
            options={
                'db_table': 'storageMapping',
            },
        ),
        migrations.CreateModel(
            name='supplymainstorage',
            fields=[
                ('supplymainstorage_id', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=50, verbose_name='ItemName')),
                ('Description', models.CharField(max_length=255, verbose_name='Description')),
                ('Unit', models.CharField(max_length=50, verbose_name='Unit')),
                ('Quantity', models.DecimalField(decimal_places=0, max_digits=50, verbose_name='Quantity')),
                ('Remaining', models.DecimalField(decimal_places=0, max_digits=50, verbose_name='Remaining')),
            ],
            options={
                'db_table': 'supplymainstorage',
            },
        ),
        migrations.CreateModel(
            name='withdrawequipment',
            fields=[
                ('withdrawequipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('withdraw_equipment_property_no', models.CharField(max_length=50, verbose_name='withdraw_equipment_property_no')),
                ('withdraw_equipment_itemname', models.CharField(max_length=50, verbose_name='withdraw_equipment_itemname')),
                ('withdraw_equipment_description', models.CharField(max_length=255, verbose_name='withdraw_equipment_description')),
                ('withdraw_equipment_brand', models.CharField(max_length=50, verbose_name='withdraw_equipment_brand')),
                ('withdraw_equipment_yearacquired', models.CharField(max_length=50, verbose_name='withdraw_yearacquired')),
                ('withdraw_equipment_issued_to', models.CharField(max_length=50, verbose_name='withdraw_equipment_issued_to')),
                ('withdraw_equipment_model_no', models.CharField(max_length=50, verbose_name='withdraw_equipment_model_no')),
                ('withdraw_equipment_serial_no', models.CharField(max_length=50, verbose_name='withdraw_equipment_serial_no')),
                ('withdraw_equipment_certifiedcorrect', models.CharField(max_length=50, verbose_name='withdraw_equipment_certifiedcorrect')),
                ('current_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='withdraw_current_date')),
            ],
            options={
                'db_table': 'withdrawequipment',
            },
        ),
        migrations.CreateModel(
            name='withdrawsupply',
            fields=[
                ('withdrawsupply_id', models.AutoField(primary_key=True, serialize=False)),
                ('withdraw_supply_department', models.CharField(max_length=50, verbose_name='withdraw_supply_department')),
                ('withdraw_supply_itemname', models.CharField(max_length=50, verbose_name='withdraw_supply_itemname')),
                ('withdraw_supply_description', models.CharField(max_length=255, verbose_name='withdraw_supply_description')),
                ('withdraw_supply_unit', models.CharField(max_length=50, verbose_name='withdraw_supply_unit')),
                ('withdraw_supply_quantity', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='withdraw_supply_quantity')),
                ('withdraw_supply_remaining', models.CharField(max_length=50, verbose_name='withdraw_supply_remaining')),
                ('current_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='withdraw_current_date')),
                ('withdraw_supply_status', models.CharField(max_length=50, verbose_name='withdraw_supply_status')),
            ],
            options={
                'db_table': 'withdrawsupply',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(default='', max_length=30, unique=True, verbose_name='username')),
                ('department', models.CharField(default='', max_length=250, unique=True, verbose_name='department')),
                ('is_department', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
