# Generated by Django 3.2.8 on 2023-01-12 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='supply_storagemapping_history',
            fields=[
                ('history_supplyStoragemapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_supplyItemName', models.CharField(max_length=50, verbose_name='Supply ItemName')),
                ('history_supplyRackNo', models.CharField(max_length=50, null=True, verbose_name='Supply Rack')),
                ('history_supplyLayerNo', models.DecimalField(decimal_places=0, max_digits=6, null=True, verbose_name='Supply Layer')),
                ('history_supplyCabinetNo', models.DecimalField(decimal_places=0, max_digits=6, null=True, verbose_name='Supply Cabinet')),
                ('history_supplyShelfNo', models.DecimalField(decimal_places=0, max_digits=6, null=True, verbose_name='Supply Shelf')),
                ('history_supplyLocation', models.CharField(max_length=50, null=True, verbose_name='Supply Location')),
                ('history_current_date', models.DateField(default=datetime.date.today, verbose_name='history_current_date')),
                ('history_current_time', models.TimeField(auto_now_add=True, verbose_name='history_current_time')),
            ],
            options={
                'db_table': 'supply_StorageMapping_history',
            },
        ),
    ]
