# Generated by Django 3.2.8 on 2023-01-05 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipment_disposed',
            fields=[
                ('equipmentDisposed_id', models.AutoField(primary_key=True, serialize=False)),
                ('disposed_equipment_property_no', models.CharField(max_length=50, unique=True, verbose_name='dispose_equipment_property_no')),
                ('disposed_equipment_itemname', models.CharField(max_length=50, verbose_name='dispose_equipment_itemname')),
                ('disposed_equipment_description', models.CharField(max_length=255, verbose_name='dispose_equipment_description')),
                ('disposed_equipment_brand', models.CharField(max_length=50, verbose_name='dispose_equipment_brand')),
                ('disposed_equipment_model_no', models.CharField(max_length=50, verbose_name='dispose_equipment_model_no')),
                ('disposed_equipment_serial_no', models.CharField(max_length=50, unique=True, verbose_name='dispose_equipment_serial_no')),
                ('disposed_equipment_receiptno', models.CharField(max_length=50, verbose_name='dispose_equipment_receiptno')),
                ('disposed_equipment_amount', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='dispose_equipment_amount')),
                ('disposed_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dispose_date')),
            ],
            options={
                'db_table': 'equipment_disposed',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='department_form',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
