# Generated by Django 4.1.3 on 2022-12-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_disposal',
            name='dispose_equipment_location',
            field=models.CharField(max_length=50, null=True, verbose_name='dispose_equipment_location'),
        ),
    ]
