# Generated by Django 3.1.14 on 2022-12-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptsupplyrequests',
            name='arequest_supply_CabinetNo',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True, verbose_name='Supply_Cabinet'),
        ),
        migrations.AddField(
            model_name='acceptsupplyrequests',
            name='arequest_supply_LayerNo',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True, verbose_name='Supply_Layer'),
        ),
        migrations.AddField(
            model_name='acceptsupplyrequests',
            name='arequest_supply_RackNo',
            field=models.CharField(max_length=50, null=True, verbose_name='Supply_Rack'),
        ),
        migrations.AddField(
            model_name='acceptsupplyrequests',
            name='arequest_supply_ShelfNo',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True, verbose_name='Supply_Shelf'),
        ),
    ]
