# Generated by Django 3.2.8 on 2022-12-15 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply_createform',
            name='createformsupply_acceptedquantity',
            field=models.CharField(max_length=50, verbose_name='createformsupply_acceptedquantity'),
        ),
        migrations.AlterField(
            model_name='supply_createform',
            name='createformsupply_department',
            field=models.CharField(max_length=50, verbose_name='createformsupply_department'),
        ),
        migrations.AlterField(
            model_name='supply_createform',
            name='createformsupply_description',
            field=models.CharField(max_length=50, verbose_name='createformsupply_description'),
        ),
        migrations.AlterField(
            model_name='supply_createform',
            name='createformsupply_unit',
            field=models.CharField(max_length=50, verbose_name='createformsupply_unit'),
        ),
        migrations.AlterField(
            model_name='supply_createform',
            name='current_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='createformsupply_current_date'),
        ),
    ]
