# Generated by Django 3.2.8 on 2022-12-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsupply',
            name='request_supply_dateaccepted',
            field=models.CharField(max_length=50, null=True, verbose_name='request_supply_dateaccepted'),
        ),
    ]
