# Generated by Django 3.2.8 on 2022-12-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment_areform_inputs',
            name='areform_inputs_totalamount',
        ),
    ]
