# Generated by Django 3.2.9 on 2022-12-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='department_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_form', models.FileField(null=True, upload_to='media')),
            ],
        ),
    ]
