# Generated by Django 3.2.8 on 2022-12-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply_email',
            name='current_date',
            field=models.CharField(max_length=50, verbose_name='currentdate'),
        ),
    ]
