# Generated by Django 3.2.8 on 2022-10-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverysupply',
            name='current_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='delivery_current_date'),
        ),
    ]
