# Generated by Django 3.2.8 on 2022-10-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverysupply',
            name='delivery_supply_remaining',
            field=models.CharField(max_length=50, verbose_name='delivery_supply_remaining'),
        ),
    ]
