# Generated by Django 3.2.9 on 2022-11-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='adminRole',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_department',
            field=models.BooleanField(default=False),
        ),
    ]
