# Generated by Django 3.2.8 on 2023-01-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_icsform_inputs',
            name='icsform_inputs_department',
            field=models.CharField(max_length=50, verbose_name='icsform_inputs_department'),
        ),
    ]
