# Generated by Django 4.1 on 2022-10-19 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnequipment',
            name='return_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='return_date'),
        ),
        migrations.AlterField(
            model_name='withdrawequipment',
            name='current_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='withdraw_current_date'),
        ),
    ]
