# Generated by Django 4.1.3 on 2022-12-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptsupplyrequests',
            name='arequest_supply_supplyCabinetNo',
        ),
        migrations.RemoveField(
            model_name='acceptsupplyrequests',
            name='arequest_supply_supplyLayerNo',
        ),
        migrations.RemoveField(
            model_name='acceptsupplyrequests',
            name='arequest_supply_supplyRackNo',
        ),
        migrations.RemoveField(
            model_name='acceptsupplyrequests',
            name='arequest_supply_supplyShelfNo',
        ),
    ]
