# Generated by Django 3.2.12 on 2022-10-13 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='acceptSupplyRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arequest_supply_itemname', models.CharField(max_length=50, verbose_name='request_supply_itemname')),
                ('arequest_supply_description', models.CharField(max_length=255, verbose_name='request_supply_description')),
                ('arequest_supply_unit', models.CharField(max_length=50, verbose_name='request_supply_unit')),
                ('arequest_supply_quantity', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='request_supply_quantity')),
                ('arequest_supply_remaining', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='request_supply_remaining')),
                ('arequest_supply_department', models.CharField(max_length=50, verbose_name='request_supply_department')),
                ('arequest_supply_status', models.CharField(max_length=50, verbose_name='request_supply_status')),
                ('current_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='request_current_date')),
            ],
            options={
                'db_table': 'acceptSupplyRequests',
            },
        ),
        migrations.DeleteModel(
            name='departmentRequests',
        ),
    ]
