# Generated by Django 3.2.8 on 2022-12-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnequipment',
            name='return_equipment_location',
            field=models.CharField(max_length=50, null=True, verbose_name='return_equipment_location'),
        ),
    ]
