# Generated by Django 4.1.3 on 2022-12-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipment_createform',
            fields=[
                ('createformequipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('createformequipment_department', models.CharField(max_length=50, unique=True, verbose_name='createformequipment_department')),
                ('createformequipment_itemname', models.CharField(max_length=50, unique=True, verbose_name='createformequipment_itemname')),
                ('createformequipment_description', models.CharField(max_length=50, unique=True, verbose_name='createformequipment_description')),
                ('createformequipment_brand', models.CharField(max_length=50, unique=True, verbose_name='createformequipment_brand')),
                ('createformequipment_acceptedquantity', models.CharField(max_length=50, unique=True, verbose_name='createformequipment_acceptedquantity')),
                ('current_date', models.CharField(max_length=50, verbose_name='currentdate')),
            ],
            options={
                'db_table': 'equipment_createform',
            },
        ),
        migrations.CreateModel(
            name='supply_createform',
            fields=[
                ('createformsupply_id', models.AutoField(primary_key=True, serialize=False)),
                ('createformsupply_department', models.CharField(max_length=50, unique=True, verbose_name='createformsupply_department')),
                ('createformsupply_unit', models.CharField(max_length=50, unique=True, verbose_name='createformsupply_unit')),
                ('createformsupply_acceptedquantity', models.CharField(max_length=50, unique=True, verbose_name='createformsupply_acceptedquantity')),
                ('current_date', models.CharField(max_length=50, verbose_name='currentdate')),
            ],
            options={
                'db_table': 'supply_createform',
            },
        ),
    ]
