# Generated by Django 3.2.9 on 2022-09-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0002_alter_deliveryequipment_delivery_equipment_quantity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='adminAcc',
        ),
    ]
