# Generated by Django 3.2.8 on 2022-12-20 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0002_requestsupply_request_supply_dateaccepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestsupply',
            name='request_supply_issued_by',
        ),
    ]
