# Generated by Django 3.2.8 on 2023-01-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0002_auto_20230106_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestequipment',
            name='request_equipment_unitcost',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='request_equipment_unitcost'),
        ),
    ]
