# Generated by Django 3.2.8 on 2022-12-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0002_auto_20221219_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptsupplyrequests',
            name='arequest_supply_requestedby',
        ),
        migrations.RemoveField(
            model_name='supply_createform',
            name='createformsupply_requestedby',
        ),
        migrations.RemoveField(
            model_name='supply_createform_inputs',
            name='createformsupply_inputs_requestedby',
        ),
    ]
