# Generated by Django 3.2.8 on 2023-01-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0002_alter_equipment_icsform_inputs_icsform_inputs_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment_areform_inputs',
            name='areform_inputs_totalamount',
        ),
    ]
