# Generated by Django 3.1.14 on 2022-12-19 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0002_auto_20221219_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply_createform_inputs',
            name='createformsupply_inputs_acceptedquantity',
        ),
        migrations.RemoveField(
            model_name='supply_createform_inputs',
            name='createformsupply_inputs_amount',
        ),
        migrations.RemoveField(
            model_name='supply_createform_inputs',
            name='createformsupply_inputs_department',
        ),
        migrations.RemoveField(
            model_name='supply_createform_inputs',
            name='createformsupply_inputs_description',
        ),
        migrations.RemoveField(
            model_name='supply_createform_inputs',
            name='createformsupply_inputs_issued_by',
        ),
        migrations.RemoveField(
            model_name='supply_createform_inputs',
            name='createformsupply_inputs_unit',
        ),
    ]
