# Generated by Django 3.2.8 on 2022-12-09 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0002_alter_returnequipment_return_equipment_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnequipment',
            name='dispose_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='return_date'),
        ),
        migrations.AlterField(
            model_name='returnequipment',
            name='return_date',
            field=models.CharField(max_length=50, verbose_name='return_date'),
        ),
    ]
