# Generated by Django 3.2.9 on 2022-10-13 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0002_auto_20221013_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptsupplyrequests',
            name='arequest_supply_department',
            field=models.CharField(max_length=50, verbose_name='arequest_supply_department'),
        ),
        migrations.AlterField(
            model_name='acceptsupplyrequests',
            name='arequest_supply_description',
            field=models.CharField(max_length=255, verbose_name='arequest_supply_description'),
        ),
        migrations.AlterField(
            model_name='acceptsupplyrequests',
            name='arequest_supply_itemname',
            field=models.CharField(max_length=50, verbose_name='arequest_supply_itemname'),
        ),
        migrations.AlterField(
            model_name='acceptsupplyrequests',
            name='arequest_supply_quantity',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='arequest_supply_quantity'),
        ),
        migrations.AlterField(
            model_name='acceptsupplyrequests',
            name='arequest_supply_remaining',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='arequest_supply_remaining'),
        ),
        migrations.AlterField(
            model_name='acceptsupplyrequests',
            name='arequest_supply_status',
            field=models.CharField(max_length=50, verbose_name='arequest_supply_status'),
        ),
        migrations.AlterField(
            model_name='acceptsupplyrequests',
            name='arequest_supply_unit',
            field=models.CharField(max_length=50, verbose_name='arequest_supply_unit'),
        ),
        migrations.AlterField(
            model_name='acceptsupplyrequests',
            name='current_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='arequest_current_date'),
        ),
    ]
