# Generated by Django 3.2.8 on 2022-12-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0002_auto_20221227_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipment_are_totalamount',
            fields=[
                ('areform_totalamount_id', models.AutoField(primary_key=True, serialize=False)),
                ('areform_totalalmount_department', models.CharField(max_length=50, unique=True, verbose_name='areform_totalamount_department')),
                ('areform_totalamount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='areform_totalamount')),
                ('current_date', models.CharField(max_length=50, verbose_name='currentdate')),
            ],
            options={
                'db_table': 'equipment_are_totalalmount',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='department_form',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
