# Generated by Django 3.2.8 on 2022-12-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0003_remove_requestsupply_request_supply_issued_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptsupplyrequests',
            name='arequest_supply_issued_by',
        ),
    ]
