# Generated by Django 3.2.8 on 2022-12-09 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0003_auto_20221210_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplymainstorage',
            name='current_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='supplymainstorage_current_date'),
        ),
    ]
