# Generated by Django 3.2.8 on 2023-01-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0003_remove_equipment_areform_inputs_areform_inputs_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_areform_inputs',
            name='areform_inputs_department',
            field=models.CharField(max_length=50, verbose_name='areform_inputs_department'),
        ),
    ]
