# Generated by Django 3.2.8 on 2022-12-30 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0003_auto_20221230_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment_are_totalamount',
            old_name='areform_totalalmount_department',
            new_name='areform_totalamount_department',
        ),
    ]
