# Generated by Django 3.2.9 on 2022-10-13 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0003_auto_20221014_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawsupply',
            name='current_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='withdraw_current_date'),
        ),
    ]
