# Generated by Django 3.2.8 on 2022-12-08 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0004_alter_equipment_email_current_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply_email',
            name='current_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='current_date'),
        ),
    ]
