# Generated by Django 3.2.8 on 2023-01-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0004_alter_equipment_areform_inputs_areform_inputs_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_are_totalamount',
            name='areform_totalamount_department',
            field=models.CharField(max_length=50, verbose_name='areform_totalamount_department'),
        ),
    ]
