# Generated by Django 3.2.8 on 2022-12-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0004_remove_acceptsupplyrequests_arequest_supply_issued_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply_createform',
            name='createformsupply_issued_by',
        ),
    ]
