# Generated by Django 3.2.8 on 2023-01-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0004_auto_20230106_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestequipment',
            name='request_equipment_iin',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='request_equipment_iin'),
        ),
        migrations.AlterField(
            model_name='requestequipment',
            name='request_equipment_totalcost',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True, verbose_name='request_equipment_totalcost'),
        ),
        migrations.AlterField(
            model_name='requestequipment',
            name='request_equipment_unit',
            field=models.CharField(default='', max_length=50, verbose_name='request_equipment_brand'),
        ),
    ]
