# Generated by Django 3.2.15 on 2022-10-07 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0004_storagemapping_remove_limitrecords_limit_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='departmentRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=50, verbose_name='ItemName')),
                ('Description', models.CharField(max_length=255, verbose_name='Description')),
                ('Brand', models.CharField(max_length=50, verbose_name='Brand')),
                ('Unit', models.CharField(max_length=50, verbose_name='Unit')),
                ('Quantity', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Unit')),
                ('Department', models.CharField(max_length=50, verbose_name='Department')),
                ('Remaining', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Remaining')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='request_date')),
            ],
            options={
                'db_table': 'departmentRequests',
            },
        ),
        migrations.AlterField(
            model_name='deliveryequipment',
            name='current_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='delivery_current_date'),
        ),
        migrations.AlterField(
            model_name='deliveryequipment',
            name='delivery_equipment_description',
            field=models.CharField(max_length=255, verbose_name='delivery_equipment_description'),
        ),
        migrations.AlterField(
            model_name='deliverysupply',
            name='current_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='delivery_current_date'),
        ),
        migrations.AlterField(
            model_name='deliverysupply',
            name='delivery_supply_description',
            field=models.CharField(max_length=255, verbose_name='delivery_supply_description'),
        ),
        migrations.AlterField(
            model_name='equipmentmainstorage',
            name='Description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='equipmentmainstorage',
            name='Remaining',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Remaining'),
        ),
        migrations.AlterField(
            model_name='limitrecords',
            name='limit_description',
            field=models.CharField(max_length=255, verbose_name='limit_description'),
        ),
        migrations.AlterField(
            model_name='limitrecords',
            name='limit_quantity',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='limit_quantity'),
        ),
        migrations.AlterField(
            model_name='requestequipment',
            name='current_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='request_current_date'),
        ),
        migrations.AlterField(
            model_name='requestequipment',
            name='request_equipment_description',
            field=models.CharField(max_length=255, verbose_name='request_equipment_description'),
        ),
        migrations.AlterField(
            model_name='requestequipment',
            name='request_equipment_quantity',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='request_equipment_quantity'),
        ),
        migrations.AlterField(
            model_name='requestsupply',
            name='request_supply_description',
            field=models.CharField(max_length=255, verbose_name='request_supply_description'),
        ),
        migrations.AlterField(
            model_name='requestsupply',
            name='request_supply_quantity',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='request_supply_quantity'),
        ),
        migrations.AlterField(
            model_name='returnequipment',
            name='return_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='return_date'),
        ),
        migrations.AlterField(
            model_name='returnequipment',
            name='return_equipment_description',
            field=models.CharField(max_length=255, verbose_name='return_equipment_description'),
        ),
        migrations.AlterField(
            model_name='storagemapping',
            name='CabinetNo',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Cabinet'),
        ),
        migrations.AlterField(
            model_name='storagemapping',
            name='LayerNo',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Layer'),
        ),
        migrations.AlterField(
            model_name='storagemapping',
            name='ShelfNo',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='supplymainstorage',
            name='Description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='supplymainstorage',
            name='Remaining',
            field=models.DecimalField(decimal_places=0, max_digits=50, verbose_name='Remaining'),
        ),
        migrations.AlterField(
            model_name='withdrawequipment',
            name='current_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='withdraw_current_date'),
        ),
        migrations.AlterField(
            model_name='withdrawequipment',
            name='withdraw_equipment_description',
            field=models.CharField(max_length=255, verbose_name='withdraw_equipment_description'),
        ),
        migrations.AlterField(
            model_name='withdrawsupply',
            name='current_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='withdraw_current_date'),
        ),
        migrations.AlterField(
            model_name='withdrawsupply',
            name='withdraw_supply_description',
            field=models.CharField(max_length=255, verbose_name='withdraw_supply_description'),
        ),
        migrations.AlterField(
            model_name='withdrawsupply',
            name='withdraw_supply_quantity',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='withdraw_supply_quantity'),
        ),
    ]
