# Generated by Django 3.2.15 on 2022-10-07 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0005_auto_20221007_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsupply',
            name='current_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='request_current_date'),
        ),
    ]
