# Generated by Django 3.2.8 on 2022-12-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0005_remove_supply_createform_createformsupply_issued_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptequipmentrequests',
            name='current_date',
        ),
        migrations.RemoveField(
            model_name='acceptequipmentrequests',
            name='current_time',
        ),
        migrations.RemoveField(
            model_name='requestequipment',
            name='current_date',
        ),
        migrations.RemoveField(
            model_name='requestequipment',
            name='current_time',
        ),
        migrations.AddField(
            model_name='acceptequipmentrequests',
            name='arequest_equipment_dateaccepted',
            field=models.CharField(max_length=50, null=True, verbose_name='arequest_equipment_dateaccepted'),
        ),
        migrations.AddField(
            model_name='acceptequipmentrequests',
            name='arequest_equipment_daterequested',
            field=models.CharField(max_length=50, null=True, verbose_name='arequest_equipment_daterequested'),
        ),
        migrations.AddField(
            model_name='requestequipment',
            name='request_equipment_dateaccepted',
            field=models.CharField(max_length=50, null=True, verbose_name='request_equipment_dateaccepted'),
        ),
        migrations.AddField(
            model_name='requestequipment',
            name='request_equipment_daterequested',
            field=models.CharField(max_length=50, null=True, verbose_name='request_equipment_daterequested'),
        ),
    ]
