# Generated by Django 3.2.8 on 2022-12-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0005_alter_supply_email_current_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply_email',
            name='current_date',
            field=models.CharField(max_length=50, verbose_name='currentdate'),
        ),
        migrations.AlterField(
            model_name='supply_email',
            name='emailsupply_acceptedquantity',
            field=models.CharField(max_length=50, verbose_name='emailsupply_acceptedquantity'),
        ),
        migrations.AlterField(
            model_name='supply_email',
            name='emailsupply_department',
            field=models.CharField(max_length=50, verbose_name='emailsupply_department'),
        ),
    ]
