# Generated by Django 3.2.8 on 2022-12-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0006_auto_20221221_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusequipmentrequest',
            name='status_equipment_dateaccepted',
            field=models.CharField(max_length=50, null=True, verbose_name='arequest_equipment_dateaccepted'),
        ),
        migrations.AddField(
            model_name='statusequipmentrequest',
            name='status_equipment_daterequested',
            field=models.CharField(max_length=50, null=True, verbose_name='arequest_equipment_daterequested'),
        ),
    ]
