# Generated by Django 3.2.8 on 2022-12-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0006_auto_20221209_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptsupplyrequests',
            name='current_date',
            field=models.CharField(max_length=50, verbose_name='currentdate'),
        ),
    ]
