# Generated by Django 3.2.8 on 2022-10-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0007_alter_requestsupply_request_supply_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsupply',
            name='request_supply_quantity',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='request_supply_quantity'),
        ),
    ]
